build:
  image: golang
  commands:
    - go get
    - go install github.com/mattn/go-sqlite3
    - CGO_ENABLED=1 go build -v -a --installsuffix cgo --ldflags=\"-s\" -o api-static
    - ls -al
    - find / -name api-static

publish:
  github_release:
    api_key: $$GITHUB_API_KEY
    files: api
    checksum: sha1

publish:
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: ldejager/microservices-demo
    tag:
      - $$COMMIT
      - latest
