build:
  image: golang
  commands:
    - go get
    - CGO_ENABLED=0 go build -v -a --installsuffix cgo --ldflags=\"-s\"

publish:
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: ldejager/microservices-demo
    tag:
      - $$COMMIT
      - latest
