build:
  image: golang
  commands:
    - go get
    - go build

publish:
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: ldejager/microservices-demo
    tag:
      - $$COMMIT
      - latest
