workspace:
  base: /go
  path: src/github.com/ldejager/microservice-demo

pipeline:
  build:
    image: golang
    environment:
      - GOOS=linux
      - GOARCH=amd64
      - CGO_ENABLED=0
      - GOPATH=/go
    commands:
      - export PATH=$PATH:$GOPATH/bin
      - go get
      - go build -a -o api
    when:
      branch: master
      event: push
  publish:
    image: plugins/docker
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: ldejager/microservice-demo
    file: Dockerfile
    tag:
      - ${DRONE_COMMIT:0:8}
      - latest
