build:
  image: golang
  commands:
    - go get
    - go install github.com/mattn/go-sqlite3
    - CGO_ENABLED=0 go build -v -a -installsuffix cgo

publish:
  github_release:
    api_key: $$GITHUB_API_KEY
    files: api
    checksum: sha1
    when:
      event: tag

publish:
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: ldejager/microservices-demo
    file: Dockerfile
    tag:
      - $$COMMIT
      - latest
