build:
  image: golang
  commands:
    - go get
    - godep save -r
    - CGO_ENABLED=0 go build -v -a --installsuffix cgo --ldflags="-s"

publish:
  github_release:
    api_key: $$GITHUB_API_KEY
    files: *
    checksum: sha1
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: ldejager/microservices-demo
    tag:
      - $$COMMIT
      - latest
