---
apiVersion: v1
kind: Service
metadata:
  name: microservice-demo
  labels:
    name: microservice-demo
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    name: microservice-demo
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: config
  type: Opaque
  data:
    db_username: ZGJfdXNlcm5hbWU=
    db_password: ZGJfcGFzc3dvcmQ=
    db_hostname: ZGJfaG9zdG5hbWU=
    db_database: ZGJfZGF0YWJhc2U=
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: microservice-demo
  labels:
    name: microservice-demo
spec:
  replicas: 1
  selector:
    name: microservice-demo
  template:
    metadata:
      labels:
        name: microservice-demo
    spec:
      containers:
        - image: ldejager/microservice-demo
          name: microservice-demo
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: config
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: config
                  key: db_password
            - name: DB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: config
                  key: db_hostname
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: config
                  key: db_database
          ports:
            - containerPort: 8000
              protocol: TCP
      volumes:
        - name: config
          secret:
            secretName: config
