---
apiVersion: v1
kind: Service
metadata:
  name: droneio
  labels:
    name: droneio
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  selector:
    name: droneio
  type: LoadBalancer
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: droneio
  labels:
    name: droneio
spec:
  replicas: 1
  selector:
    name: droneio
  template:
    metadata:
      labels:
        name: droneio
    spec:
      containers:
        - image: drone/drone
          name: droneio
          env:
            - name: SERVER_ADDR
              value: ":443"
            - name: SERVER_KEY
              value: /etc/secrets/key
            - name: SERVER_CERT
              value: /etc/secrets/cert
            - name: DATABASE_DRIVER
              value: sqlite3
            - name: DATABASE_CONFIG
              value: /var/lib/drone/drone.sqlite
            - name: REMOTE_DRIVER
              value: github
            - name: REMOTE_CONFIG
              valueFrom:
                secretKeyRef:
                  name: droneiossl
                  key: remoteconfig
          ports:
            - containerPort: 443
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/secrets
              name: droneiossl
              readOnly: true
            - mountPath: /var/lib/drone
              name: droneio-sqlite-db
            - mountPath: /var/run/docker.sock
              name: docker-socket
            - mountPath: /var/lib/docker
              name: docker-lib
      volumes:
        - name: droneiossl
          secret:
            secretName: droneiossl
        - name: droneio-sqlite-db
          gcePersistentDisk:
            pdName: droneio-sqlite-db
            fsType: ext4
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: docker-lib
          hostPath:
            path: /var/lib/docker
