---
apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    name: jenkins
spec:
  replicas: 1
  template:
    metadata:
      name: jenkins
      labels:
        name: jenkins
    spec:
      containers:
        - name: jenkins
          image: rwxlabs/jenkins-master:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: 4Gi
              cpu: 500m
          ports:
            - name: jenkins-http
              containerPort: 8080
            - name: jenkins-disco
              containerPort: 50000
          volumeMounts:
            - name: build-data
              mountPath: /var/jenkins_home
      volumes:
        - name: build-data
          gcePersistentDisk:
            pdName: build-data
            fsType: ext4
---
kind: Service
apiVersion: v1
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    name: jenkins
spec:
  ports:
  - name: ui
    port: 8080
    targetPort: jenkins-http
    protocol: TCP
  - name: discovery
    port: 50000
    targetPort: jenkins-disco
    protocol: TCP
  selector:
    name: jenkins
